//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffClockProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class DWATAMB
    {
        public string DWCXOGGP { get; set; }
        public string DWCXOGGF { get; set; }
        public string DWCXSPE1 { get; set; }
        public string DWCXSPE2 { get; set; }
        public string DWCXSPE3 { get; set; }
        public string DWCXSPE4 { get; set; }
        public string DWCXSPE5 { get; set; }
        public string DWCXSPE6 { get; set; }
        public string DWCXSPE7 { get; set; }
        public string DWCXSPE8 { get; set; }
        public string DWCXSPE9 { get; set; }
        public string DWCXSPE10 { get; set; }
        public Nullable<short> DWCDPROP { get; set; }
        public Nullable<short> DWCDLIV1 { get; set; }
        public Nullable<short> DWCDLIV2 { get; set; }
        public Nullable<System.DateTime> DWDTISTI { get; set; }
        public Nullable<System.DateTime> DWDTAGGT { get; set; }
        public Nullable<System.DateTime> DWDTVALD { get; set; }
        public Nullable<System.DateTime> DWDTVALA { get; set; }
        public Nullable<System.DateTime> DWDTANNU { get; set; }
        public Nullable<System.DateTime> DWDTCANC { get; set; }
        public Nullable<short> DWFLATTI { get; set; }
        public string DWCDUTEN { get; set; }
        public int DWPRUKEY { get; set; }
    }
}
